<<<<<<< HEAD
# Agent3 - (K=1, n=6, stochastique)
name: "Agent3"
env_name: "CartPole-v1"
K: 1
n_steps: 6
stochastic_rewards: true
lr_actor: 0.00001  
lr_critic: 0.001
gamma: 0.99
max_steps: 500000
entropy_coef: 0.01
eval_freq: 20000


=======
#agent3.yaml
# configs/agent3.yaml
K: 1
n_steps: 6
stochastic_rewards: false
lr_actor: 1e-5
lr_critic: 1e-3
gamma: 0.99
>>>>>>> origin/aziz
